---
concord_version: 0.4.2
concord_enable_at_least_once: "true"
concord_mesos_version: 0.28.0
concord_java_flags:
  - "server"
  - "XX:+UseConcMarkSweepGC"
  - "XX:+HeapDumpOnOutOfMemoryError"
concord_java_options:
  "DMESOS_NATIVE_JAVA_LIBRARY" : /usr/local/lib/libmesos-{{ concord_mesos_version }}.so
