---
concord_version: 0.3.14
concord_mesos_version: 0.23.1
concord_java_flags:
  - "server"
  - "XX:+UseConcMarkSweepGC"
  - "XX:+HeapDumpOnOutOfMemoryError"
concord_java_options:
  "DMESOS_NATIVE_JAVA_LIBRARY" : /usr/local/lib/libmesos-{{ concord_mesos_version }}.so
